# Generated by Django 5.2.13 on 2026-04-30 20:33

import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfoliovideo_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorprofile',
            name='avatar_file',
            field=models.FileField(blank=True, upload_to=portfolio.models.profile_avatar_upload_to),
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='cname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='other_contacts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='role',
            field=models.CharField(choices=[('editor', 'Editor'), ('client', 'Client')], default='editor', max_length=10),
        ),
        migrations.CreateModel(
            name='FollowRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relationships', to='portfolio.editorprofile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relationships', to='portfolio.editorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('follower', 'followed'), name='unique_follow_relationship')],
            },
        ),
    ]
