# Generated by Django 5.2.13 on 2026-05-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_editorprofile_avatar_file_editorprofile_cname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorprofile',
            name='clients_served',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='completed_projects',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VideoReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('star', 'Star'), ('like', 'Like'), ('love', 'Love'), ('fire', 'Fire')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reactions', to='portfolio.editorprofile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='portfolio.portfoliovideo')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('video', 'profile', 'reaction_type'), name='unique_video_reaction_per_type')],
            },
        ),
    ]
