# Generated by Django 5.2.13 on 2026-05-02 10:31

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_videostarrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliovideo',
            name='uploaded_file',
            field=models.FileField(blank=True, storage=portfolio.models.PortfolioVideoStorage(), upload_to=portfolio.models.portfolio_video_upload_to),
        ),
    ]
