# Generated by Django 5.2.13 on 2026-05-02 12:53

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_portfoliovideo_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorprofile',
            name='avatar_file',
            field=models.FileField(blank=True, max_length=500, upload_to=portfolio.models.profile_avatar_upload_to),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='uploaded_file',
            field=models.FileField(blank=True, max_length=500, storage=portfolio.models.PortfolioVideoStorage(), upload_to=portfolio.models.portfolio_video_upload_to),
        ),
    ]
