# Generated by Django 5.2.13 on 2026-05-03 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_download_request_snapshots_and_grants(apps, schema_editor):
    VideoDownloadRequest = apps.get_model('portfolio', 'VideoDownloadRequest')
    VideoDownloadGrant = apps.get_model('portfolio', 'VideoDownloadGrant')

    db_alias = schema_editor.connection.alias
    requests = (
        VideoDownloadRequest.objects.using(db_alias)
        .select_related('video', 'video__profile')
        .all()
    )
    for download_request in requests:
        dirty_fields = []
        if not download_request.video_title_snapshot:
            download_request.video_title_snapshot = download_request.video.title
            dirty_fields.append('video_title_snapshot')
        if not download_request.video_preview_url_snapshot:
            download_request.video_preview_url_snapshot = download_request.video.thumbnail_url
            dirty_fields.append('video_preview_url_snapshot')
        if not download_request.telegram_chat_id:
            download_request.telegram_chat_id = download_request.video.profile.telegram_chat_id
            dirty_fields.append('telegram_chat_id')
        if dirty_fields:
            download_request.save(update_fields=dirty_fields)

        if download_request.status == 'approved':
            VideoDownloadGrant.objects.using(db_alias).update_or_create(
                source_request=download_request,
                defaults={
                    'user': download_request.requester,
                    'video': download_request.video,
                    'granted_by': download_request.reviewed_by,
                    'is_active': True,
                    'revoked_at': None,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_editorprofile_telegram_chat_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='videodownloadrequest',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='videodownloadrequest',
            name='telegram_message_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='videodownloadrequest',
            name='video_preview_url_snapshot',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='videodownloadrequest',
            name='video_title_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='editorprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('client', 'Client')], default='editor', max_length=10),
        ),
        migrations.AlterField(
            model_name='videodownloadrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=12),
        ),
        migrations.CreateModel(
            name='EditorSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.editorprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='portfolio.skilltag')),
            ],
            options={
                'ordering': ['skill__sort_order', 'skill__name'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'skill'), name='unique_editor_skill')],
            },
        ),
        migrations.CreateModel(
            name='VideoDownloadGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_video_downloads', to=settings.AUTH_USER_MODEL)),
                ('source_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_grant', to='portfolio.videodownloadrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_download_grants', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_grants', to='portfolio.portfoliovideo')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'video'), name='unique_active_video_download_grant')],
            },
        ),
        migrations.RunPython(
            backfill_download_request_snapshots_and_grants,
            migrations.RunPython.noop,
        ),
    ]
