# Generated by Django 5.2.13 on 2026-04-30 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='Video editor on Ela-sam Portfolio Show.')),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('telegram', models.CharField(blank=True, max_length=64)),
                ('whatsapp', models.CharField(blank=True, max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('content_type', models.CharField(choices=[('short', 'Short Content'), ('long', 'Long Content')], max_length=5)),
                ('category', models.CharField(choices=[('Commercial / Ads', 'Commercial / Ads'), ('Wedding', 'Wedding'), ('YouTube Content', 'YouTube Content'), ('Documentary', 'Documentary'), ('Music Video', 'Music Video'), ('Social Media', 'Social Media'), ('Corporate', 'Corporate')], max_length=32)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='portfolio.editorprofile')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
