# Generated by Django 5.2.13 on 2026-04-30 20:01

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_seed_sample_portfolios'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliovideo',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to=portfolio.models.portfolio_video_upload_to),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='video_source',
            field=models.CharField(choices=[('link', 'Link'), ('upload', 'Upload'), ('both', 'Both')], default='link', max_length=10),
        ),
        migrations.AlterField(
            model_name='portfoliovideo',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
