# Generated by Django 5.2.13 on 2026-05-02 13:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_editorprofile_avatar_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='editorprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='frame_rate',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='original_bitrate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='original_file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='original_format',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='original_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='original_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok (9:16)'), ('youtube', 'YouTube (16:9)'), ('instagram', 'Instagram / Reels'), ('facebook', 'Facebook'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='storage_public_id',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='portfoliovideo',
            name='watermark_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='VideoDownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('request_message', models.TextField(blank=True)),
                ('owner_response_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_download_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_video_download_requests', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='portfolio.portfoliovideo')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('stream_token_issued', 'Stream token issued'), ('stream_redirected', 'Stream redirected'), ('like_toggled', 'Like toggled'), ('rating_submitted', 'Rating submitted'), ('download_requested', 'Download requested'), ('download_approved', 'Download approved'), ('download_rejected', 'Download rejected'), ('download_link_issued', 'Download link issued'), ('download_redirected', 'Download redirected')], max_length=32)),
                ('viewer_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_access_logs', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='portfolio.portfoliovideo')),
                ('download_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='portfolio.videodownloadrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('download_request', 'Download request'), ('download_approved', 'Download approved'), ('download_rejected', 'Download rejected')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_notifications', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_notifications', to='portfolio.portfoliovideo')),
                ('download_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_notifications', to='portfolio.videodownloadrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_likes', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_likes', to='portfolio.portfoliovideo')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_ratings_public', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_ratings', to='portfolio.portfoliovideo')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='videodownloadrequest',
            constraint=models.UniqueConstraint(fields=('requester', 'video'), name='unique_video_download_request_per_user'),
        ),
        migrations.AddConstraint(
            model_name='videolike',
            constraint=models.UniqueConstraint(fields=('video', 'viewer_hash'), name='unique_public_video_like'),
        ),
        migrations.AddConstraint(
            model_name='videorating',
            constraint=models.UniqueConstraint(fields=('video', 'viewer_hash'), name='unique_public_video_rating'),
        ),
    ]
